version: '3'

services:
    server:
        build:
            context: ./server
            args:
                app_env: ${APP_ENV}
        volumes:
            - ./server:/go/src/github.com/jurebajt/go-docker-dev-setup/server
        ports:
            - '5000:8080'
        tty: true
